language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/sacad-build
    - $HOME/.cache/sacad-test
matrix:
  include:
    - python: "3.3"
      env: WINDOWS=0 PYPI_DEPLOY=0
    - python: "3.4"
      env: WINDOWS=1 PYPI_DEPLOY=0
    - python: "3.5"
      env: WINDOWS=0 PYPI_DEPLOY=0
    - python: "3.5-dev"
      env: WINDOWS=0 PYPI_DEPLOY=0
    - python: "3.6"
      env: WINDOWS=0 PYPI_DEPLOY=1
    - python: "3.6-dev"
      env: WINDOWS=0 PYPI_DEPLOY=0
    - python: "3.7-dev"
      env: WINDOWS=0 PYPI_DEPLOY=0
  allow_failures:
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "3.7-dev"
  fast_finish: true
before_install:
  - "sudo add-apt-repository -y ppa:ubuntu-wine/ppa"
  - "sudo apt-get -q update"
  - "pip install -U pip"
install:
  - "sudo apt-get -V install libxml2-dev libxslt1-dev"  # lxml dependencies
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "sudo apt-get -V install optipng jpegoptim"
  - "if [ $WINDOWS -eq 1 ]; then sudo apt-get -V install wine p7zip-full; fi"
script:
  - "TEST_DL_CACHE_DIR=$HOME/.cache/sacad-test travis_retry coverage run --source=sacad setup.py test"
  - "if [ $WINDOWS -eq 1 ]; then pushd win && TEST_DL_CACHE_DIR=$HOME/.cache/sacad-test DOWNLOAD_DIR=$HOME/.cache/sacad-build make test && popd; fi"
after_success:
  - "coveralls"
before_deploy:
  - "if [ $PYPI_DEPLOY -eq 1 ]; then sudo add-apt-repository -y ppa:marutter/c2d4u; fi"  # to get newer pandoc
  - "if [ $PYPI_DEPLOY -eq 1 ]; then sudo apt-get -q update; fi"
  - "if [ $PYPI_DEPLOY -eq 1 ]; then sudo apt-get -V install pandoc; fi"
  - "if [ $PYPI_DEPLOY -eq 1 ]; then pip install pypandoc; fi"
  - "if [ $PYPI_DEPLOY -eq 1 ]; then pip install restructuredtext_lint && t=$(mktemp --suffix=.rst) && pandoc README.md -o $t && rst-lint $t; fi"
  - "if [ $WINDOWS -eq 1 ]; then pushd win && make all && popd; fi"
deploy:
  - provider: releases
    api_key:
      secure: "B6gBCH4ecbVXrGKwEehal5tbYOtyvzbDvdwCXnAf87h18CIuRdzIMRkFIYd06cIYXzTtkptaSvC1euZYWUP8NVSoiZmpLNumQCJMANh/eDcBKrfm4fFvsTwq5fQ3NDauJH4VJreh73pex8ke+NmyRy+BfgEj4FO8pxBbN9/Q/Sw="
    file:
      - "win/sacad_win.zip"
      - "win/sacad_win.7z"
      - "win/sacad_win.exe"
    skip_cleanup: true
    on:
      tags: true
      branch: master
      python: "3.4"
  - provider: pypi
    user: desbma
    password:
      secure: "WJGhFJrX/S42EhXIj6oEmOxEoMSHLAtVyZe7EQm0ho5A5MH0NR64H8pPlrPuzHl/AZmxiSz/70G5xGlV6anaxjEOH8FFQ+lrjwgp0H4a1hVImFUZi45QHRq1E2GhzxMEsaAq1K5BdAYXOkIHCa4+jsFbZRcrDNO72jCIJfvX1q0="
    on:
      tags: true
      branch: master
      python: "3.6"
notifications:
  email:
    recipients:
      - secure: "g5HaEKHvapImYa1t/2DfW86YAEDUwAcPlbKJ/SZSUkH9POCtdc0TayLGuS9ByY/2cOXiUyCwbQ3r3qMs9p14ev6wKo5NMOYJsR3ijDB8Qh6ri182TmeXWlWLQrLWAZD5NTYdhUoK4taEAbnLV+AQuZwAUBkyX8tFGHQre3/IYl4="
    on_success: always
    on_failure: always
