language: python
python:
  - "3.3"
  - "3.4"
install:
  - "sudo apt-get -yV install libxml2-dev libxslt1-dev"  # lxml dependencies
  - "pip install -r requirements.txt"
  - "pip install coveralls"
  - "sudo apt-get -yV install optipng jpegoptim"
script:
  - "coverage run --source=sacad setup.py test"
after_success:
  - "coveralls"
